### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by riccardoruspoli** [staaldraad/async_wake_ios#1]
Can you please upload these files that are missing?

![schermata 2017-12-20 alle 17 11 41](https://user-images.githubusercontent.com/24920356/34216543-eae6edfa-e5a8-11e7-9cf5-b4bd95570632.png)

**Comment by mortezaezzabady** [comment]
yes `tar` and `bearbins.tar` are missing!

**Comment by staaldraad** [comment]
hey! sorry I didn't realise :)

Adding them!

**Comment by staaldraad** [comment]
https://github.com/staaldraad/async_wake_ios/commit/4330e94bc5c6de5c2141157b0e3bb12a740695d2

and Updated paths;
https://github.com/staaldraad/async_wake_ios/commit/66a50fcab0fcb769320a3a4b0efea383d76a06bf
